(in-package :hextris)

(defun parse-args (args)
  (iter (initially (setq args-tail args))
        (for pname = (car args-tail))
        (for pvalue = (car (cdr args-tail)))
        (for args-tail next (if (eq args-tail nil) (terminate) (rest (rest args-tail))))
        (when (string= "-f" (string-downcase pname))
          (collect pvalue into files))
        (when (String= "-t" (string-downcase pname))
          (for time-limit = pvalue))
        (when (String= "-m" (string-downcase pname))
          (for memory-limit = pvalue))
        (when (string= "-p" (string-downcase pname))
          (collect pvalue into phrases))
        (finally (return (list files time-limit memory-limit phrases)))))

(defun main (args)
  (destructuring-bind (files time-limit memory-limit phrases)
      (parse-args (rest args))
    (let ((solutions (iter (for fname in files)
                           ) (collect nil)))
      )))
